LLM_WEIGHT = 0.6
STYLO_WEIGHT = 0.4

AI_THRESHOLD = 0.72
HUMAN_THRESHOLD = 0.35


def combine_scores(llm_score, stylo_score):
    return LLM_WEIGHT * llm_score + STYLO_WEIGHT * stylo_score


def classify(combined_score):
    if combined_score >= AI_THRESHOLD:
        return "likely_ai"
    if combined_score <= HUMAN_THRESHOLD:
        return "likely_human"
    return "uncertain"


def generate_label(combined_score):
    attribution = classify(combined_score)
    pct = round(combined_score * 100)

    if attribution == "likely_ai":
        text = (
            f"⚠️ Likely AI-Generated: Our system found strong signals — from both "
            f"language-model review and writing-style analysis — that this content was "
            f"generated by AI ({pct}% confidence). If you believe this is a mistake, you can "
            f"appeal this classification."
        )
    elif attribution == "likely_human":
        text = (
            f"✅ Likely Human-Written: Our system found this content consistent with typical "
            f"human writing patterns, based on language-model review and writing-style analysis "
            f"({pct}% AI-likelihood)."
        )
    else:
        text = (
            f"❓ Uncertain Origin: Our system could not confidently determine whether this "
            f"content is AI-generated or human-written — the signals were mixed ({pct}% "
            f"AI-likelihood). This content is shown without a definitive attribution claim."
        )

    return attribution, text
