import json
import os
import re

from groq import Groq

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


LLM_PROMPT = """You are an assistant that estimates whether a piece of text was written by a human or generated by an AI language model.

Consider: uniformity of tone, use of hedging phrases ("it is important to note", "on the other hand"), evenness of sentence structure, presence of a distinctive personal voice, idiosyncrasies, typos, or casual/informal markers.

Respond with ONLY a JSON object, no other text, in this exact format:
{"ai_probability": <float between 0 and 1, where 1.0 means certainly AI-generated and 0.0 means certainly human-written>, "reasoning": "<one sentence explanation>"}

Text to assess:
\"\"\"
{TEXT}
\"\"\"
"""


def llm_signal(text):
    """Returns {"ai_probability": float 0-1, "reasoning": str}."""
    client = _get_client()
    prompt = LLM_PROMPT.replace("{TEXT}", text)
    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
        max_tokens=200,
    )
    raw = completion.choices[0].message.content.strip()
    try:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        parsed = json.loads(match.group(0) if match else raw)
        ai_probability = float(parsed.get("ai_probability", 0.5))
        ai_probability = max(0.0, min(1.0, ai_probability))
        reasoning = str(parsed.get("reasoning", ""))
    except (json.JSONDecodeError, AttributeError, ValueError, TypeError):
        ai_probability = 0.5
        reasoning = "Could not parse model response; defaulting to uncertain."
    return {"ai_probability": ai_probability, "reasoning": reasoning}


_SENTENCE_SPLIT_RE = re.compile(r"[.!?]+(?:\s|$)")
_WORD_RE = re.compile(r"[A-Za-z']+")
_CONTRACTION_RE = re.compile(r"\b\w+'(m|re|s|t|d|ll|ve)\b", re.IGNORECASE)
_CASUAL_PRONOUN_RE = re.compile(r"\b(i|me|my|honestly|literally|lol|gonna|wanna)\b", re.IGNORECASE)


def _sentence_length_variance_score(text):
    sentences = [s.strip() for s in _SENTENCE_SPLIT_RE.split(text) if s.strip()]
    lengths = [len(_WORD_RE.findall(s)) for s in sentences if _WORD_RE.findall(s)]
    if len(lengths) < 2:
        return 0.5
    mean = sum(lengths) / len(lengths)
    if mean == 0:
        return 0.5
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    stdev = variance ** 0.5
    cv = stdev / mean
    # Lower coefficient of variation -> more uniform -> more AI-like.
    # cv of ~0.0 => score 1.0 (very AI-like); cv of >=0.8 => score 0.0 (very human-like)
    score = 1.0 - min(cv / 0.8, 1.0)
    return score


def _type_token_ratio_score(text):
    words = [w.lower() for w in _WORD_RE.findall(text)]
    if len(words) < 5:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Very low diversity (repetitive/formulaic) -> more AI-like.
    # ttr <= 0.4 => score 1.0; ttr >= 0.8 => score 0.0
    score = 1.0 - min(max((ttr - 0.4) / 0.4, 0.0), 1.0)
    return score


def _informality_score(text):
    contractions = len(_CONTRACTION_RE.findall(text))
    casual = len(_CASUAL_PRONOUN_RE.findall(text))
    ellipses = text.count("..")
    multi_exclaim = len(re.findall(r"!{2,}", text))
    lowercase_starts = len(re.findall(r"(?:^|[.!?]\s+)[a-z]", text))

    informality_hits = contractions + casual + ellipses + multi_exclaim + lowercase_starts
    # More informality markers -> more human-like -> lower AI-likeness.
    # 0 hits => score 1.0 (AI-like); 5+ hits => score 0.0 (human-like)
    score = 1.0 - min(informality_hits / 5.0, 1.0)
    return score


def stylo_signal(text):
    """Returns {"ai_likeness": float 0-1, "components": {...}}."""
    sentence_score = _sentence_length_variance_score(text)
    ttr_score = _type_token_ratio_score(text)
    informality = _informality_score(text)

    ai_likeness = 0.4 * sentence_score + 0.3 * ttr_score + 0.3 * informality
    return {
        "ai_likeness": ai_likeness,
        "components": {
            "sentence_length_variance_score": round(sentence_score, 3),
            "type_token_ratio_score": round(ttr_score, 3),
            "informality_score": round(informality, 3),
        },
    }
